export const ICON_NAMES = {
  AuthLogologo: require('../../assets/icons/AuthLogologo.png'),
  eye: require('../../assets/icons/eye.png'),
  eyeOff: require('../../assets/icons/eyeOff.png'),
  logo1: require('../../assets/icons/logo1.png'),
  logo2: require('../../assets/icons/logo2.png'),
  asterisk: require('../../assets/icons/asterisk.png'),
  frame: require('../../assets/icons/frame.png'),
  checkbox: require('../../assets/icons/checkbox.png'),
  drop: require('../../assets/icons/drop.png'),
  Loader: require('../../assets/icons/Loader.png'),
  reminders: require('../../assets/icons/reminders.png'),
  questions: require('../../assets/icons/questions.png'),
  messages: require('../../assets/icons/messages.png'),
  calendar: require('../../assets/icons/calendar.png'),
  vitamin: require('../../assets/icons/vitamin.png'),
  doctor: require('../../assets/icons/doctor.png'),
  burgerBar: require('../../assets/icons/burgerBar.png'),
  lock: require('../../assets/icons/lock.png'),
  email: require('../../assets/icons/email.png'),
  hide: require('../../assets/icons/hide.png'),
  healthy: require('../../assets/icons/healthy.png'),
  upload: require('../../assets/icons/upload.gif'),
  attachment: require('../../assets/icons/attachment.gif'),
  mic: require('../../assets/icons/mic.png'),
  back: require('../../assets/icons/back.png'),
  location: require('../../assets/icons/location.gif'),
  star: require('../../assets/icons/star.png'),

  baseWave1: require('../../assets/icons/baseWave1.png'),
  baseWave2: require('../../assets/icons/baseWave2.png'),

  bottomBar:{
    icon1: require('../../assets/icons/homeLight.png'),
    icon2: require('../../assets/icons/calendarDark.png'),
    icon3: require('../../assets/icons/reminder.png'),
    icon4: require('../../assets/icons/chatLight.png'),
  },
  bottomBarFocused:{
    icon1: require('../../assets/icons/doctor.png'),
    icon2: require('../../assets/icons/doctor.png'),
    icon3: require('../../assets/icons/doctor.png'),
    icon4: require('../../assets/icons/doctor.png'),
  }
};
